name: PR Code Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install

      - name: Linting check
        run: npm run lint

      - name: Schema check
        run: npm run schema:gen

      - name: Success
        run: echo "🚧 Build successful 🚧"
